---
nomad_version: "0.11.1"
nomad_checksum: "sha256:97e3f3a8ead2c32919ad4d7912713805cb79a39d3ba7932125be5bbb2e9ebd21"
nomad_install_path: /usr/local/consul
nomad_dc: dc1
nomad_is_server: no
nomad_leader_group: baron
nomad_bootstrap_expect: "{{ groups[nomad_leader_group] | length }}"
nomad_retry_join: ' [{% for host in groups[nomad_leader_group] %}"{{ host }}"{% if not loop.last %}, {% endif %}{% endfor %}]'
